using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SourceGenerators;
using Xunit;

namespace MvvmToolGenerators.Tests;

public class MvvmToolGeneratorsTests
{
    private const string ClassWithAttributePropsAndMethods = """
                                           using MvvmTool;

                                           namespace SourceGenerators.Sample;

                                           [INotifyPropertyChanged]
                                           public partial class ViewModelAttr
                                           {
                                               [ObservableProperty]
                                               private int _testPropAttr0;

                                               [ObservableProperty]
                                               private int _testPropAttr1;

                                               [RelayCommand]
                                               private void TestMethodAttr0(object obj)
                                               {
                                                   TestPropAttr0++;
                                                   TestPropAttr1++;
                                               }

                                               [RelayCommand]
                                               private void TestMethodAttr1(object obj)
                                               {
                                                   TestPropAttr0++;
                                                   TestPropAttr1++;
                                               }
                                           }
                                           """;

    private const string ExpectedGeneratedClassText = """
                                                      // <auto-generated/>

                                                      using System;
                                                      using System.Collections.Generic;

                                                      namespace TestNamespace;

                                                      partial class Vector3
                                                      {
                                                          public IEnumerable<string> Report()
                                                          {
                                                              yield return $"X:{this.X}";
                                                              yield return $"Y:{this.Y}";
                                                              yield return $"Z:{this.Z}";
                                                          }
                                                      }

                                                      """;

    [Fact]
    public void PropertyAndCommandGenerator_GeneratorValidation_OutputEqual()
    {
        // 1) Arrange
        // Create an instance of the source generator.
        var generator = new PropertyAndCommandGenerator();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(nameof(MvvmToolGeneratorsTests),
            [
                CSharpSyntaxTree.ParseText(ClassWithAttributePropsAndMethods)
                // CSharpSyntaxTree.ParseText(TypesGenerator.Types),
            ],
            [
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        // 2) ActW
        // Run generators and retrieve all results.
        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();

        foreach (SyntaxTree tree in runResult.GeneratedTrees)
        {
            // Complex generators should be tested using text comparison.
            string actual = tree.GetText().ToString();

            // 3) Assert
            Assert.Equal(ExpectedGeneratedClassText, actual, ignoreLineEndingDifferences: true);
        }
    }
}