using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators;

[Generator]
public class ObservablePropertyGenerator : ISourceGenerator
{
    private const string Namespace = "MvvmTool";
    private const string AttributesSource =
        $$"""
          // <auto-generated/>

          namespace {{Namespace}}
          {
              [System.AttributeUsage(System.AttributeTargets.Field)]
              public class ObservablePropertyAttribute : System.Attribute { }

              [System.AttributeUsage(System.AttributeTargets.Field)]
              public class INotifyPropertyChangedAttribute : System.Attribute { }

              [System.AttributeUsage(System.AttributeTargets.Field)]
              public class RelayCommandAttribute : System.Attribute { }
          }
          """;

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        AddAttributes(context);

        if (context.SyntaxReceiver is not SyntaxReceiver receiver)
        {
            return;
        }

        Compilation compilation = context.Compilation;
        var fieldsByClass = new Dictionary<INamedTypeSymbol, List<IFieldSymbol>>(SymbolEqualityComparer.Default);

        foreach (FieldDeclarationSyntax fieldDecl in receiver.CandidateFields)
        {
            SemanticModel model = compilation.GetSemanticModel(fieldDecl.SyntaxTree);

            foreach (VariableDeclaratorSyntax variable in fieldDecl.Declaration.Variables)
            {
                if (model.GetDeclaredSymbol(variable) is not IFieldSymbol fieldSymbol)
                {
                    continue;
                }

                var hasAttr = fieldSymbol.GetAttributes()
                    .Any(a => a.AttributeClass?.Name == "ObservablePropertyAttribute");

                if (!hasAttr)
                {
                    continue;
                }

                INamedTypeSymbol classSymbol = fieldSymbol.ContainingType;
                if (!fieldsByClass.TryGetValue(classSymbol, out var list))
                {
                    list = new List<IFieldSymbol>();
                    fieldsByClass[classSymbol] = list;
                }

                list.Add(fieldSymbol);
            }
        }

        foreach (var kvp in fieldsByClass)
        {
            INamedTypeSymbol classSymbol = kvp.Key;
            var fields = kvp.Value;
            var source = GenerateClassWithProperties(classSymbol, fields);
            context.AddSource($"{classSymbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static void AddAttributes(GeneratorExecutionContext context)
    {
        context.AddSource("ObservablePropertyAttribute.g.cs",
            SourceText.From(AttributesSource, Encoding.UTF8));
    }

    private static string GenerateClassWithProperties(INamedTypeSymbol classSymbol, List<IFieldSymbol> fields)
    {
        var sb = new StringBuilder();

        var ns = classSymbol.ContainingNamespace?.ToDisplayString();
        if (!string.IsNullOrWhiteSpace(ns) && !classSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns} {{");
        }

        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {classSymbol.Name} : INotifyPropertyChanged");
        sb.AppendLine("{");
        sb.AppendLine("    public event PropertyChangedEventHandler PropertyChanged;");

        foreach (IFieldSymbol field in fields)
        {
            var fieldName = field.Name;
            fieldName = fieldName.TrimStart('_');
            var propertyName = char.ToUpper(fieldName[0]) + fieldName.Substring(1);
            var typeName = field.Type.ToDisplayString();

            sb.AppendLine($$"""

                                public {{typeName}} {{propertyName}}
                                {
                                    get => {{fieldName}};
                                    set
                                    {
                                        if (!EqualityComparer<{{typeName}}>.Default.Equals({{fieldName}}, value))
                                        {
                                            {{fieldName}} = value;
                                            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof({{propertyName}})));
                                        }
                                    }
                                }
                            """);
        }

        sb.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(ns) && !classSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private class SyntaxReceiver : ISyntaxReceiver
    {
        public List<FieldDeclarationSyntax> CandidateFields { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is FieldDeclarationSyntax field && field.AttributeLists.Count > 0)
            {
                CandidateFields.Add(field);
            }
        }
    }
}
