using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MvvmToolGenerators.Generators;

[Generator]
public class NotifyPropertyChangedImplementationGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not SyntaxReceiver receiver)
        {
            return;
        }

        foreach (ClassDeclarationSyntax classDeclarationSyntax in receiver.ClassesToProcess)
        {
            var (source, fileName) = GetSource(context, classDeclarationSyntax);

            if (source == null || fileName == null)
            {
                continue;
            }

            context.AddSource(fileName, source);
        }
    }

    private static (SourceText?, string?) GetSource(GeneratorExecutionContext context,
        ClassDeclarationSyntax classDeclarationSyntax)
    {
        SemanticModel semanticModel = context.Compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);
        if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
        {
            return (null, null);
        }

        string? namespaceName = classSymbol.ContainingNamespace?.ToDisplayString();
        bool hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
        string className = classSymbol.Name;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        if (hasNamespace)
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"public partial class {className} : System.ComponentModel.INotifyPropertyChanged");
        sb.AppendLine("{");
        sb.AppendLine("    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;");
        sb.AppendLine("}"); // End of class

        if (hasNamespace)
        {
            sb.AppendLine("}"); // End of namespace
        }

        SourceText source = SourceText.From(sb.ToString(), Encoding.UTF8);
        string fileName = $"{classSymbol.Name}.INotifyPropertyChanged.Implementation.g.cs";

        return (source, fileName);
    }

    private class SyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> ClassesToProcess { get; } = [];

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax classDecl &&
                classDecl.AttributeLists
                    .Any(al => al.Attributes
                        .Any(a => a.Name.ToString() == "INotifyPropertyChanged")))
            {
                ClassesToProcess.Add(classDecl);
            }
        }
    }
}